### PR TITLE
Add minPoints prop

### PR DESCRIPTION
**Pull request by jimsheen**
Thanks very much for this package it's great! Please let me know if you would like any more information on this PR

Minimum number of points to form a cluster.

https://github.com/mapbox/supercluster#options

Added to the supercluster package ~two months ago

### CODE REVIEW

**Comment by AntonLukovtsev** [comment]
@jimsheen Hi! When your changes will be merge?

**Comment by AntonLukovtsev** [comment]
Guys, it will awesome if you will merge it!

**Comment by clarios6** [comment]
Yep, works great :D

**Comment by axelkennedal** [comment]
Please merge this @venits 😄

**Comment by venits** [comment]
I implemented those changes in `3.4.0` version of library.

Thank you so much for contributing 💕

**Pull request closed without merging**
