### PR TITLE
Fix spiral marker not using custom marker + Fix Marker disappear

### PR DESCRIPTION
**Pull request by kperreau**
This is a PR fixing spiral marker not using custom marker.
And it fix marker hide/disappear some time refer to this issue: https://github.com/venits/react-native-map-clustering/issues/129

### CODE REVIEW

**Comment by GunnarAK** [comment]
I have tried your pull-request in my project locally. Cloned it and imported it in my package.json (and some other tweaks to be able to install deps from outside the project root).

MapView renders fine, BUT now the markers don't even try to render before disappearing. Sometimes 1 sticks its head up, but disappears when I try to pan to it (not clicking on marker).

Reverting back to `react-native-maps`'s MapView shows my markers (total 43).
I have tested both of the MapView components with my custom markers and the default ones from react-native-maps. No difference in rendering there.

This issue persists on the following Android devices for me:
- Samsung Galaxy J2 (SM-J260F) - 1GB RAM
- Samsung Galaxy S5 Neo (SM-G903F) - 2GB RAM
- LG Nexus 5X - 1GB RAM

Meanwhile it works perfectly on my OnePlus 6 with 8GB RAM (A6003)
So this leads me to believe it's RAM-related but I might be blindsighted by the number. I don't have any other devices to test on.
`tracksViewChanges` is toggled via component state of every marker.
```
componentDidUpdate(prevProps: Props) {
  if (
    prevProps.station !== this.props.station // set true only when props changed
  ) {
    this.setState({ tracksViewChanges: true });
  } else if (this.state.tracksViewChanges) {
    // set to false immediately after rendering with tracksViewChanges is true
    this.setState({ tracksViewChanges: false });
  }
}
```

**Comment by venits** [comment]
Hi 👋
I released a new version of this module: `3.2.0`. This change is there.
I had to make some additional changes.

Thank you for your contribution ❤️

**Comment by benov84** [comment]
Still not working for me, marker dissapers

**Comment by jackimatin** [comment]
any solution for this issue?

please help me...

**Comment by JAZzmiX** [comment]
Still not working

**Pull request closed without merging**
