### PR TITLE
Spiderfier view of the same location markers

### PR DESCRIPTION
**Pull request by chetanparmar95**
Hi @venits  and all contributors of this library,
I had submitted [this](https://github.com/venits/react-native-map-clustering/issues/122) issue with different account for my requirement then I check this library doesn't support this. I thought this is the opportunity for me to contribute something. I did something to achieve that functionality that you might like. Please have a look and if you need any change then please let me know. Thank you. 

This is the result of the markers with same coordinates:
spider_lib

spider2

### CODE REVIEW

**Comment by venits** [comment]
@chetanparmar95 wow, that looks amazing :D 

I am going to test and merge it this week 👍

**Comment by chetanparmar95** [comment]
@venits Why you did not merge my changes? for me its showing only 0 line contribution :(

**Comment by venits** [comment]
Hmm I did merged your pull request into master. I don't know why it shows 0 lines 🤔

**Comment by chetanparmar95** [comment]
> Hmm I did merged your pull request into master. I don't know why it shows 0 lines 🤔

I can see your new branch with the changes

**Comment by venits** [comment]
Hmm I think I found a problem.

This repo doesn't include `.prettierrc`.

I forked your pull request to make some minor changes and it turned out that my default prettier config is different than yours. It resulted in slightly changing all the lines of code you provided.

 Nevertheless you still have `Contributor` badge so you can still pin this repo in your GitHub profile 👍

**Comment by chetanparmar95** [comment]
> Hmm I think I found a problem.
> 
> This repo doesn't include `.prettierrc`.
> 
> I forked your pull request to make some minor changes and it turned out that my default prettier config is different than yours. It resulted in slightly changing all the lines of code you provided.
> 
> Nevertheless you still have `Contributor` badge so you can still pin this repo in your GitHub profile 👍

Yeah, but I can see you have created a new pull request of your own with my changes. I don't have any problem. It's your choice. 👍

**Review by Makaveloco — APPROVED** [review]
- ~~~~

**Pull request merged**
